// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { secureStorage } from '@/lib/secureStorage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// SECURITY: Use secure storage for auth tokens
// - Mobile (iOS/Android): Uses encrypted platform storage (Keychain/EncryptedSharedPreferences)
// - Web: Uses sessionStorage (safer than localStorage, cleared on tab close)
// This prevents XSS attacks from stealing auth tokens
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any -- Supabase's Storage interface doesn't match our secure wrapper exactly
    storage: secureStorage as any,
    persistSession: true,
    autoRefreshToken: true,
  }
});